### ISSUE TITLE
Create Login screen/view

### ISSUE THREAD

**Issue by kinow** [kinow/cylc-web#12]
Related to #2 , after creating a basic JWT backend example, realized we still do not have a UI with the form/fields for authentication.

- ~An [example with Material](https://codepen.io/joshadamous/pen/yyyqJZ)~ (Not clear what's the license)
- ~Another [example with Material](https://dzone.com/articles/angular-5-material-design-login-application)~ (Not clear what's the license)
- The [page about Forms from Vuetify](https://vuetifyjs.com/en/components/forms) has some examples
- ~A [Vuetify example](https://codepen.io/arpitg/pen/mMvZNR)~ (Not clear what's the license)
- ~A [gist with a Vuetify example](https://gist.github.com/SirPoot-/82d22463549ae02c7cbd27e8832b59a7), alas without screen shot~ (Not clear what's the license)
- Another [example](http://jasonwatmore.com/post/2018/07/14/vue-vuex-user-registration-and-login-tutorial-example)
- ~And [http://designify.me/tutorials/how-to-create-a-beautiful-material-design-login-form-with-html-css/](http://designify.me/tutorials/how-to-create-a-beautiful-material-design-login-form-with-html-css/)~ (Not clear what's the license)
- ~One from [Colorlib](https://colorlib.com/wp/template/login-form-v10/)~ (CC By 3.0, we would have to add a footer/header note about the author)

**Comment by kinow** [comment]
There's really only Vuetify form, and this one http://jasonwatmore.com/post/2018/07/14/vue-vuex-user-registration-and-login-tutorial-example that have the license that we can use.

So will have a look at these two and try to write something from scratch :-)

**Comment by kinow** [comment]
Result so far

![image](https://user-images.githubusercontent.com/304786/52386879-be029700-2aec-11e9-96be-96d29616cb6a.png)

Had to implement the layout mechanism from [this post](https://itnext.io/anyway-heres-how-to-create-a-multiple-layout-system-with-vue-and-vue-router-b379baa91a05) in order to avoid the drawer & toolbar from being displayed for a couple seconds until the application was fully rendered.

Because of this, in the routes, we now **must** specify the `meta: { layout: default|empty }`.

**Comment by kinow** [comment]
Going to combine with the code from the application layouts examples from vuetify, and have it looking similar to this example: https://vuetifyjs.com/en/examples/layouts/centered

**Comment by hjoliver** [comment]
Looks nice :grin:

**Comment by kinow** [comment]
Thanks @hjoliver ! Hopefully good enough for the initial version. Wanted to add Cylc's icon to the top of the card (that clear area in the middle of the page is within an element from Material UI called "Card")... but that would take another 30 - 90 minutes fiddling with CSS/HTML.

Good enough for now I think. 

![image](https://user-images.githubusercontent.com/304786/52450105-8ce29f00-2b9e-11e9-91df-fbaf58709813.png)
