### ISSUE TITLE
Choose which validation framework to use

### ISSUE THREAD

**Issue by kinow** [kinow/cylc-web#13]
Creating the login form (#12) the need to validate the fields appeared. Vuetify comes with two libraries ready to be used for that: 

- [vee-validate](https://baianat.github.io/vee-validate/)
- [Vuelidate](https://monterail.github.io/vuelidate/)

Both look good, but we need to pick one...

**Comment by kinow** [comment]
Spent the morning reading about it, after finishing up the travis-ci & coverage issue.

- vee-validate has more contributors & stars in GitHub (197, 5K), comparing to vuelidate (23, 3k).
- vee-validate has still more users in npm ([npm trend for both](https://www.npmtrends.com/vee-validate-vs-vuelidate))
![image](https://user-images.githubusercontent.com/304786/52672152-dc9bde80-2f81-11e9-9f87-f60167d35f80.png)
- vee-validate's last commit was 29 minutes ago, while vuelidate was from September last year
- vee-validate is heavier than vuelidate as a dependency (vee-validate is 8 times bigger than vuelidate)
![image](https://user-images.githubusercontent.com/304786/52672592-2a651680-2f83-11e9-8924-c03a92a40abc.png)
![image](https://user-images.githubusercontent.com/304786/52672742-934c8e80-2f83-11e9-8661-55198a7dbb3d.png)

* vee-validate users directives for validation. So you put your validation logic in the templates.

```html
<input v-validate="'required|email'">
```

Vuelidate, on the other hand, uses model validation. So in your code you set the model, and in your component's code you specify the validation desired.

```html
<input v-model="name" @input="$v.name.$touch()">
```

```javascript
import { required, email } from 'vuelidate/lib/validators'

export default {  
  data () {
    return {
      name: ''
    }
  },
  validations: {
    name: {
      required,
      email
    }
  }
}
```

It may be easier to have custom validation with Vuelidate. While vee-validate seems better for smaller projects with limited validation.

* Vuelidate's documentation and examples is better. You can easily find the code for the examples. While vee-validate uses Codepen.
* Vuelidate contains example code for Vuex integration/validation

**Comment by kinow** [comment]
Will go with vee-validate in the end. Even though it is much bigger than Vuelidate. The main reason is the state of the two open source projects. I thought it was weird that vee-validate had low activity given the amount of posts saying good things about it.

Looks like one of the main developers left the company behind vee-validate, and now the project is going through some restructure?

![image](https://user-images.githubusercontent.com/304786/52674143-93e72400-2f87-11e9-9657-a2c19f2e4b84.png)

From: https://github.com/monterail/vuelidate/issues/369#issuecomment-445225102

**Comment by kinow** [comment]
Some good links found while researching about the two tools:

* [How I started loving Vue](https://gist.github.com/Igogrek/58046e1dda1638012299129bd0ae4ffd)
* [Vuelidate: Rethinking Validations for Vue.js](https://www.monterail.com/blog/vuelidate-vuejs)

**Comment by kinow** [comment]
And in case Vuelidate gets active again, we can just start using it, as it's not super hard. However, if on the other hand we adopted Vuelidate now, and needed a feature/bug fix/etc for validating things like job execution forms for Cylc, we would have to patch it locally or hack the code. Which is much worse than suffering with bigger bundle size.

**Comment by kinow** [comment]
Added one example in the user profile page for the user e-mail.

![image](https://user-images.githubusercontent.com/304786/52674953-0fe26b80-2f8a-11e9-9673-86cbbb607a9b.png)

![image](https://user-images.githubusercontent.com/304786/52674981-1bce2d80-2f8a-11e9-81ff-82597a196a29.png)

![image](https://user-images.githubusercontent.com/304786/52674993-25579580-2f8a-11e9-964b-03bafe16fc52.png)

![image](https://user-images.githubusercontent.com/304786/52675000-2ee0fd80-2f8a-11e9-9b49-445438cc0d2c.png)

**Comment by shentao** [comment]
@kinow Vuelidate is back! It will, however, take us some time to get through all that happened to the project before we can introduce meaningful changes.

**Comment by kinow** [comment]
Thanks @shentao ! I will keep an eye on Vuelidate. As we are still in early stages in Cylc, we might still be able to switch the validation framework. And I really liked Vuelidate :slightly_smiling_face:

**Comment by shentao** [comment]
Let me know if there is a way for us to help!
