### ISSUE TITLE
Set up Travis CI integration

### ISSUE THREAD

**Issue by kinow** [kinow/cylc-web#17]
- [x] running unit tests #15 
- [ ] running functional tests #16 
- [x] reporting coverage
- [x] check security & static analysis issues

(Maybe even report issues to Riot some day?)

**Comment by kinow** [comment]
Searched for "vue js project travis.yml npm", and found [this good example](https://github.com/viljamis/vue-design-system/blob/master/.travis.yml). It appears to work well. Time to test on Travis.

**Comment by kinow** [comment]
Activated Travis-CI build: https://travis-ci.org/kinow/cylc-web

**Comment by kinow** [comment]
Ooohh, running! 

![image](https://user-images.githubusercontent.com/304786/52606201-963d7580-2ed6-11e9-9443-5e2e949c6d99.png)

**Comment by kinow** [comment]
Comparing to Cylc, setting up coverage for this project was a breeze. Here's the report on Codecov.

![image](https://user-images.githubusercontent.com/304786/52606972-66dc3800-2ed9-11e9-9029-357834857187.png)

**Comment by kinow** [comment]
Dependencies security is covered by GitHub :tada: :rocket: 

![image](https://user-images.githubusercontent.com/304786/52607074-d5b99100-2ed9-11e9-9e4d-f1d6809ede8b.png)

**Comment by kinow** [comment]
Cypress [does not offer coverage](https://github.com/cypress-io/cypress/issues/346) reports. They focus only in integration tests. The issue linked contains comments from the project where they explain that they believe it is hard - and not quite useful - to have coverage for integration tests.

I would still prefer to know that one part of my code was tested with some integration tests, than not knowing it. But for now I think we will have to postpone the complete coverage, and have only unit test for now. The unit test is also missing the `.vue` files.

**Comment by hjoliver** [comment]
Cypress - never heard of that (wow, there's so much great stuff out there!).
